//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: user_api.proto

package api

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"

	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoReq) Reset() {
	*x = GetInfoReq{}
	mi := &file_user_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoReq) ProtoMessage() {}

func (x *GetInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoReq.ProtoReflect.Descriptor instead.
func (*GetInfoReq) Descriptor() ([]byte, []int) {
	return file_user_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetInfoReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_user_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_user_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_user_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_user_api_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	RealName      string                 `protobuf:"bytes,3,opt,name=RealName,proto3" json:"RealName,omitempty"`
	Mail          string                 `protobuf:"bytes,4,opt,name=Mail,proto3" json:"Mail,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Env           string                 `protobuf:"bytes,6,opt,name=Env,proto3" json:"Env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_api_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *User) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

var File_user_api_proto protoreflect.FileDescriptor

const file_user_api_proto_rawDesc = "" +
	"\n" +
	"\x0euser_api.proto\x12(org.apache.dubbogo.samples.shop.user.api\"(\n" +
	"\n" +
	"GetInfoReq\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"(\n" +
	"\fRegisterResp\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\"\x96\x01\n" +
	"\x04User\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12\x1a\n" +
	"\bRealName\x18\x03 \x01(\tR\bRealName\x12\x12\n" +
	"\x04Mail\x18\x04 \x01(\tR\x04Mail\x12\x14\n" +
	"\x05Phone\x18\x05 \x01(\tR\x05Phone\x12\x10\n" +
	"\x03Env\x18\x06 \x01(\tR\x03Env2\xd3\x03\n" +
	"\vUserService\x12r\n" +
	"\bRegister\x12..org.apache.dubbogo.samples.shop.user.api.User\x1a6.org.apache.dubbogo.samples.shop.user.api.RegisterResp\x12k\n" +
	"\x05Login\x122.org.apache.dubbogo.samples.shop.user.api.LoginReq\x1a..org.apache.dubbogo.samples.shop.user.api.User\x12r\n" +
	"\fTimeoutLogin\x122.org.apache.dubbogo.samples.shop.user.api.LoginReq\x1a..org.apache.dubbogo.samples.shop.user.api.User\x12o\n" +
	"\aGetInfo\x124.org.apache.dubbogo.samples.shop.user.api.GetInfoReq\x1a..org.apache.dubbogo.samples.shop.user.api.UserB;Z9github.com/apache/dubbo-go-samples/task/shop/user/api;apib\x06proto3"

var (
	file_user_api_proto_rawDescOnce sync.Once
	file_user_api_proto_rawDescData []byte
)

func file_user_api_proto_rawDescGZIP() []byte {
	file_user_api_proto_rawDescOnce.Do(func() {
		file_user_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_api_proto_rawDesc), len(file_user_api_proto_rawDesc)))
	})
	return file_user_api_proto_rawDescData
}

var file_user_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_api_proto_goTypes = []any{
	(*GetInfoReq)(nil),   // 0: org.apache.dubbogo.samples.shop.user.api.GetInfoReq
	(*LoginReq)(nil),     // 1: org.apache.dubbogo.samples.shop.user.api.LoginReq
	(*RegisterResp)(nil), // 2: org.apache.dubbogo.samples.shop.user.api.RegisterResp
	(*User)(nil),         // 3: org.apache.dubbogo.samples.shop.user.api.User
}
var file_user_api_proto_depIdxs = []int32{
	3, // 0: org.apache.dubbogo.samples.shop.user.api.UserService.Register:input_type -> org.apache.dubbogo.samples.shop.user.api.User
	1, // 1: org.apache.dubbogo.samples.shop.user.api.UserService.Login:input_type -> org.apache.dubbogo.samples.shop.user.api.LoginReq
	1, // 2: org.apache.dubbogo.samples.shop.user.api.UserService.TimeoutLogin:input_type -> org.apache.dubbogo.samples.shop.user.api.LoginReq
	0, // 3: org.apache.dubbogo.samples.shop.user.api.UserService.GetInfo:input_type -> org.apache.dubbogo.samples.shop.user.api.GetInfoReq
	2, // 4: org.apache.dubbogo.samples.shop.user.api.UserService.Register:output_type -> org.apache.dubbogo.samples.shop.user.api.RegisterResp
	3, // 5: org.apache.dubbogo.samples.shop.user.api.UserService.Login:output_type -> org.apache.dubbogo.samples.shop.user.api.User
	3, // 6: org.apache.dubbogo.samples.shop.user.api.UserService.TimeoutLogin:output_type -> org.apache.dubbogo.samples.shop.user.api.User
	3, // 7: org.apache.dubbogo.samples.shop.user.api.UserService.GetInfo:output_type -> org.apache.dubbogo.samples.shop.user.api.User
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_api_proto_init() }
func file_user_api_proto_init() {
	if File_user_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_api_proto_rawDesc), len(file_user_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_api_proto_goTypes,
		DependencyIndexes: file_user_api_proto_depIdxs,
		MessageInfos:      file_user_api_proto_msgTypes,
	}.Build()
	File_user_api_proto = out.File
	file_user_api_proto_goTypes = nil
	file_user_api_proto_depIdxs = nil
}
