// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: proto/user.proto
package user

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// UserProviderName is the fully-qualified name of the UserProvider service.
	UserProviderName = "user.UserProvider"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserProviderGetUserProcedure is the fully-qualified name of the UserProvider's GetUser RPC.
	UserProviderGetUserProcedure = "/user.UserProvider/GetUser"
)
const (
	// UserProviderV2Name is the fully-qualified name of the UserProviderV2 service.
	UserProviderV2Name = "user.UserProviderV2"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserProviderV2SayHelloProcedure is the fully-qualified name of the UserProviderV2's SayHello RPC.
	UserProviderV2SayHelloProcedure = "/user.UserProviderV2/SayHello"
)

var (
	_ UserProvider = (*UserProviderImpl)(nil)

	_ UserProviderV2 = (*UserProviderV2Impl)(nil)
)

// UserProvider is a client for the user.UserProvider service.
type UserProvider interface {
	GetUser(ctx context.Context, req *GetUserRequest, opts ...client.CallOption) (*GetUserResponse, error)
}

// UserProviderV2 is a client for the user.UserProviderV2 service.
type UserProviderV2 interface {
	SayHello(ctx context.Context, req *SayHelloRequest, opts ...client.CallOption) (*SayHelloResponse, error)
}

// NewUserProvider constructs a client for the user.UserProvider service.
func NewUserProvider(cli *client.Client, opts ...client.ReferenceOption) (UserProvider, error) {
	conn, err := cli.DialWithInfo("user.UserProvider", &UserProvider_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &UserProviderImpl{
		conn: conn,
	}, nil
}

func SetConsumerUserProvider(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &UserProvider_ClientInfo)
}

// UserProviderImpl implements UserProvider.
type UserProviderImpl struct {
	conn *client.Connection
}

func (c *UserProviderImpl) GetUser(ctx context.Context, req *GetUserRequest, opts ...client.CallOption) (*GetUserResponse, error) {
	resp := new(GetUserResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "GetUser", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

// NewUserProviderV2 constructs a client for the user.UserProviderV2 service.
func NewUserProviderV2(cli *client.Client, opts ...client.ReferenceOption) (UserProviderV2, error) {
	conn, err := cli.DialWithInfo("user.UserProviderV2", &UserProviderV2_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &UserProviderV2Impl{
		conn: conn,
	}, nil
}

func SetConsumerUserProviderV2(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &UserProviderV2_ClientInfo)
}

// UserProviderV2Impl implements UserProviderV2.
type UserProviderV2Impl struct {
	conn *client.Connection
}

func (c *UserProviderV2Impl) SayHello(ctx context.Context, req *SayHelloRequest, opts ...client.CallOption) (*SayHelloResponse, error) {
	resp := new(SayHelloResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "SayHello", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var UserProvider_ClientInfo = client.ClientInfo{
	InterfaceName: "user.UserProvider",
	MethodNames:   []string{"GetUser"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*UserProviderImpl)
		dubboCli.conn = conn
	},
}
var UserProviderV2_ClientInfo = client.ClientInfo{
	InterfaceName: "user.UserProviderV2",
	MethodNames:   []string{"SayHello"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*UserProviderV2Impl)
		dubboCli.conn = conn
	},
}

// UserProviderHandler is an implementation of the user.UserProvider service.
type UserProviderHandler interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

func RegisterUserProviderHandler(srv *server.Server, hdlr UserProviderHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &UserProvider_ServiceInfo, opts...)
}

func SetProviderUserProvider(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &UserProvider_ServiceInfo)
}

// UserProviderV2Handler is an implementation of the user.UserProviderV2 service.
type UserProviderV2Handler interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
}

func RegisterUserProviderV2Handler(srv *server.Server, hdlr UserProviderV2Handler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &UserProviderV2_ServiceInfo, opts...)
}

func SetProviderUserProviderV2(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &UserProviderV2_ServiceInfo)
}

var UserProvider_ServiceInfo = server.ServiceInfo{
	InterfaceName: "user.UserProvider",
	ServiceType:   (*UserProviderHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "GetUser",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetUserRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetUserRequest)
				res, err := handler.(UserProviderHandler).GetUser(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
var UserProviderV2_ServiceInfo = server.ServiceInfo{
	InterfaceName: "user.UserProviderV2",
	ServiceType:   (*UserProviderV2Handler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "SayHello",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(SayHelloRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*SayHelloRequest)
				res, err := handler.(UserProviderV2Handler).SayHello(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
