// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: gate/gate.proto
package gate

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// GateServiceName is the fully-qualified name of the GateService service.
	GateServiceName = "gate.GateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GateServiceSendProcedure is the fully-qualified name of the GateService's Send RPC.
	GateServiceSendProcedure = "/gate.GateService/Send"
)

var (
	_ GateService = (*GateServiceImpl)(nil)
)

// GateService is a client for the gate.GateService service.
type GateService interface {
	Send(ctx context.Context, req *SendRequest, opts ...client.CallOption) (*Result, error)
}

// NewGateService constructs a client for the gate.GateService service.
func NewGateService(cli *client.Client, opts ...client.ReferenceOption) (GateService, error) {
	conn, err := cli.DialWithInfo("gate.GateService", &GateService_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &GateServiceImpl{
		conn: conn,
	}, nil
}

func SetConsumerGateService(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &GateService_ClientInfo)
}

// GateServiceImpl implements GateService.
type GateServiceImpl struct {
	conn *client.Connection
}

func (c *GateServiceImpl) Send(ctx context.Context, req *SendRequest, opts ...client.CallOption) (*Result, error) {
	resp := new(Result)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "Send", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var GateService_ClientInfo = client.ClientInfo{
	InterfaceName: "gate.GateService",
	MethodNames:   []string{"Send"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*GateServiceImpl)
		dubboCli.conn = conn
	},
}

// GateServiceHandler is an implementation of the gate.GateService service.
type GateServiceHandler interface {
	Send(context.Context, *SendRequest) (*Result, error)
}

func RegisterGateServiceHandler(srv *server.Server, hdlr GateServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &GateService_ServiceInfo, opts...)
}

func SetProviderGateService(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &GateService_ServiceInfo)
}

var GateService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "gate.GateService",
	ServiceType:   (*GateServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "Send",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(SendRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*SendRequest)
				res, err := handler.(GateServiceHandler).Send(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
