# my global config
global:
  scrape_interval: 120s
  evaluation_interval: 120s
  external_labels:
    monitor: 'metric-dubbo-go-server'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 120s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'metric-dubbo-server'
    scheme: http
    scrape_interval: 10s
    static_configs:
      # 这里需要写本机机器的ip
      - targets: [ 'localhost:8080' ]