// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v3.21.12
// source: order_api.proto

package api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderClient interface {
	SubmitOrder(ctx context.Context, in *OrderReq, opts ...grpc_go.CallOption) (*OrderResp, common.ErrorWithAttachment)
}

type orderClient struct {
	cc *triple.TripleConn
}

type OrderClientImpl struct {
	SubmitOrder func(ctx context.Context, in *OrderReq) (*OrderResp, error)
}

func (c *OrderClientImpl) GetDubboStub(cc *triple.TripleConn) OrderClient {
	return NewOrderClient(cc)
}

func (c *OrderClientImpl) XXX_InterfaceName() string {
	return "org.apache.dubbogo.samples.shop.order.api.Order"
}

func NewOrderClient(cc *triple.TripleConn) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) SubmitOrder(ctx context.Context, in *OrderReq, opts ...grpc_go.CallOption) (*OrderResp, common.ErrorWithAttachment) {
	out := new(OrderResp)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/SubmitOrder", in, out)
}

// OrderServer is the server API for Order service.
// All implementations must embed UnimplementedOrderServer
// for forward compatibility
type OrderServer interface {
	SubmitOrder(context.Context, *OrderReq) (*OrderResp, error)
	mustEmbedUnimplementedOrderServer()
}

// UnimplementedOrderServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedOrderServer) SubmitOrder(context.Context, *OrderReq) (*OrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOrder not implemented")
}
func (s *UnimplementedOrderServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedOrderServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedOrderServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &Order_ServiceDesc
}
func (s *UnimplementedOrderServer) XXX_InterfaceName() string {
	return "org.apache.dubbogo.samples.shop.order.api.Order"
}

func (UnimplementedOrderServer) mustEmbedUnimplementedOrderServer() {}

// UnsafeOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServer will
// result in compilation errors.
type UnsafeOrderServer interface {
	mustEmbedUnimplementedOrderServer()
}

func RegisterOrderServer(s grpc_go.ServiceRegistrar, srv OrderServer) {
	s.RegisterService(&Order_ServiceDesc, srv)
}

func _Order_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("SubmitOrder", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// Order_ServiceDesc is the grpc_go.ServiceDesc for Order service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var Order_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "org.apache.dubbogo.samples.shop.order.api.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "SubmitOrder",
			Handler:    _Order_SubmitOrder_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "order_api.proto",
}
