//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: order_api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           int64                  `protobuf:"varint,1,opt,name=Sku,proto3" json:"Sku,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Receiver      string                 `protobuf:"bytes,5,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderReq) Reset() {
	*x = OrderReq{}
	mi := &file_order_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReq) ProtoMessage() {}

func (x *OrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReq.ProtoReflect.Descriptor instead.
func (*OrderReq) Descriptor() ([]byte, []int) {
	return file_order_api_proto_rawDescGZIP(), []int{0}
}

func (x *OrderReq) GetSku() int64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *OrderReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OrderReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *OrderReq) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type OrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           string                 `protobuf:"bytes,1,opt,name=Env,proto3" json:"Env,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Receiver      string                 `protobuf:"bytes,4,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResp) Reset() {
	*x = OrderResp{}
	mi := &file_order_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResp) ProtoMessage() {}

func (x *OrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResp.ProtoReflect.Descriptor instead.
func (*OrderResp) Descriptor() ([]byte, []int) {
	return file_order_api_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResp) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *OrderResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrderResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *OrderResp) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

var File_order_api_proto protoreflect.FileDescriptor

const file_order_api_proto_rawDesc = "" +
	"\n" +
	"\x0forder_api.proto\x12)org.apache.dubbogo.samples.shop.order.api\"~\n" +
	"\bOrderReq\x12\x10\n" +
	"\x03Sku\x18\x01 \x01(\x03R\x03Sku\x12\x14\n" +
	"\x05Count\x18\x02 \x01(\x05R\x05Count\x12\x18\n" +
	"\aAddress\x18\x03 \x01(\tR\aAddress\x12\x14\n" +
	"\x05Phone\x18\x04 \x01(\tR\x05Phone\x12\x1a\n" +
	"\bReceiver\x18\x05 \x01(\tR\bReceiver\"i\n" +
	"\tOrderResp\x12\x10\n" +
	"\x03Env\x18\x01 \x01(\tR\x03Env\x12\x18\n" +
	"\aAddress\x18\x02 \x01(\tR\aAddress\x12\x14\n" +
	"\x05Phone\x18\x03 \x01(\tR\x05Phone\x12\x1a\n" +
	"\bReceiver\x18\x04 \x01(\tR\bReceiver2\x81\x01\n" +
	"\x05Order\x12x\n" +
	"\vSubmitOrder\x123.org.apache.dubbogo.samples.shop.order.api.OrderReq\x1a4.org.apache.dubbogo.samples.shop.order.api.OrderRespB<Z:github.com/apache/dubbo-go-samples/task/shop/order/api;apib\x06proto3"

var (
	file_order_api_proto_rawDescOnce sync.Once
	file_order_api_proto_rawDescData []byte
)

func file_order_api_proto_rawDescGZIP() []byte {
	file_order_api_proto_rawDescOnce.Do(func() {
		file_order_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_api_proto_rawDesc), len(file_order_api_proto_rawDesc)))
	})
	return file_order_api_proto_rawDescData
}

var file_order_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_api_proto_goTypes = []any{
	(*OrderReq)(nil),  // 0: org.apache.dubbogo.samples.shop.order.api.OrderReq
	(*OrderResp)(nil), // 1: org.apache.dubbogo.samples.shop.order.api.OrderResp
}
var file_order_api_proto_depIdxs = []int32{
	0, // 0: org.apache.dubbogo.samples.shop.order.api.Order.SubmitOrder:input_type -> org.apache.dubbogo.samples.shop.order.api.OrderReq
	1, // 1: org.apache.dubbogo.samples.shop.order.api.Order.SubmitOrder:output_type -> org.apache.dubbogo.samples.shop.order.api.OrderResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_api_proto_init() }
func file_order_api_proto_init() {
	if File_order_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_api_proto_rawDesc), len(file_order_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_api_proto_goTypes,
		DependencyIndexes: file_order_api_proto_depIdxs,
		MessageInfos:      file_order_api_proto_msgTypes,
	}.Build()
	File_order_api_proto = out.File
	file_order_api_proto_goTypes = nil
	file_order_api_proto_depIdxs = nil
}
