version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    restart: on-failure

  nacos:
    image: nacos/nacos-server:1.2.0
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
    healthcheck:
      test: "curl --fail http://127.0.0.1:8848/nacos/v1/console/health/liveness || exit 1"
      interval: 5s
