apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-uniform-router-demo-server2
  labels:
    app: k8s-uniform-router-demo-server2
  namespace: dubbo-workplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-uniform-router-demo-server2
  template:
    metadata:
      labels:
        app: k8s-uniform-router-demo-server2
    spec:
      containers:
        - name: k8s-uniform-router-demo-server2
          image: k8s-uniform-router-demo-server2:latest
          imagePullPolicy: IfNotPresent # first find in local
