apiVersion: v1
kind: Service
metadata:
  name: server-demo
  namespace: dubbo-demo
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: server-demo
  ports:
    - name: grpc-tri
      port: 50052
      targetPort: 50052
