// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: greet.proto
package greet

import (
	"context"
	"net/http"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// GreeterName is the fully-qualified name of the Greeter service.
	GreeterName = "helloworld.Greeter"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GreeterSayHelloProcedure is the fully-qualified name of the Greeter's SayHello RPC.
	GreeterSayHelloProcedure = "/helloworld.Greeter/SayHello"
	// GreeterSayHelloStreamProcedure is the fully-qualified name of the Greeter's SayHelloStream RPC.
	GreeterSayHelloStreamProcedure = "/helloworld.Greeter/SayHelloStream"
)

var (
	_ Greeter = (*GreeterImpl)(nil)

	_ Greeter_SayHelloStreamClient = (*GreeterSayHelloStreamClient)(nil)

	_ Greeter_SayHelloStreamServer = (*GreeterSayHelloStreamServer)(nil)
)

// Greeter is a client for the helloworld.Greeter service.
type Greeter interface {
	SayHello(ctx context.Context, req *HelloRequest, opts ...client.CallOption) (*User, error)
	SayHelloStream(ctx context.Context, opts ...client.CallOption) (Greeter_SayHelloStreamClient, error)
}

// NewGreeter constructs a client for the greet.Greeter service.
func NewGreeter(cli *client.Client, opts ...client.ReferenceOption) (Greeter, error) {
	conn, err := cli.DialWithInfo("helloworld.Greeter", &Greeter_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &GreeterImpl{
		conn: conn,
	}, nil
}

func SetConsumerGreeter(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &Greeter_ClientInfo)
}

// GreeterImpl implements Greeter.
type GreeterImpl struct {
	conn *client.Connection
}

func (c *GreeterImpl) SayHello(ctx context.Context, req *HelloRequest, opts ...client.CallOption) (*User, error) {
	resp := new(User)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "SayHello", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *GreeterImpl) SayHelloStream(ctx context.Context, opts ...client.CallOption) (Greeter_SayHelloStreamClient, error) {
	stream, err := c.conn.CallBidiStream(ctx, "SayHelloStream", opts...)
	if err != nil {
		return nil, err
	}
	rawStream := stream.(*triple_protocol.BidiStreamForClient)
	return &GreeterSayHelloStreamClient{rawStream}, nil
}

type Greeter_SayHelloStreamClient interface {
	Spec() triple_protocol.Spec
	Peer() triple_protocol.Peer
	Send(*HelloRequest) error
	RequestHeader() http.Header
	CloseRequest() error
	Recv() (*User, error)
	ResponseHeader() http.Header
	ResponseTrailer() http.Header
	CloseResponse() error
}

type GreeterSayHelloStreamClient struct {
	*triple_protocol.BidiStreamForClient
}

func (cli *GreeterSayHelloStreamClient) Send(msg *HelloRequest) error {
	return cli.BidiStreamForClient.Send(msg)
}

func (cli *GreeterSayHelloStreamClient) Recv() (*User, error) {
	msg := new(User)
	if err := cli.BidiStreamForClient.Receive(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

var Greeter_ClientInfo = client.ClientInfo{
	InterfaceName: "helloworld.Greeter",
	MethodNames:   []string{"SayHello", "SayHelloStream"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*GreeterImpl)
		dubboCli.conn = conn
	},
}

// GreeterHandler is an implementation of the helloworld.Greeter service.
type GreeterHandler interface {
	SayHello(context.Context, *HelloRequest) (*User, error)
	SayHelloStream(context.Context, Greeter_SayHelloStreamServer) error
}

func RegisterGreeterHandler(srv *server.Server, hdlr GreeterHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &Greeter_ServiceInfo, opts...)
}

func SetProviderGreeter(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &Greeter_ServiceInfo)
}

type Greeter_SayHelloStreamServer interface {
	Send(*User) error
	Recv() (*HelloRequest, error)
	Spec() triple_protocol.Spec
	Peer() triple_protocol.Peer
	RequestHeader() http.Header
	ResponseHeader() http.Header
	ResponseTrailer() http.Header
	Conn() triple_protocol.StreamingHandlerConn
}

type GreeterSayHelloStreamServer struct {
	*triple_protocol.BidiStream
}

func (srv *GreeterSayHelloStreamServer) Send(msg *User) error {
	return srv.BidiStream.Send(msg)
}

func (srv GreeterSayHelloStreamServer) Recv() (*HelloRequest, error) {
	msg := new(HelloRequest)
	if err := srv.BidiStream.Receive(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

var Greeter_ServiceInfo = server.ServiceInfo{
	InterfaceName: "helloworld.Greeter",
	ServiceType:   (*GreeterHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "SayHello",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(HelloRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*HelloRequest)
				res, err := handler.(GreeterHandler).SayHello(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "SayHelloStream",
			Type: constant.CallBidiStream,
			StreamInitFunc: func(baseStream interface{}) interface{} {
				return &GreeterSayHelloStreamServer{baseStream.(*triple_protocol.BidiStream)}
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				stream := args[0].(Greeter_SayHelloStreamServer)
				if err := handler.(GreeterHandler).SayHelloStream(ctx, stream); err != nil {
					return nil, err
				}
				return nil, nil
			},
		},
	},
}
