version: '3.5'

services:
  zk:
    image: zookeeper
    container_name: zk
    networks:
      - dubbo
    ports:
      - 2181:2181
# 网络
networks:
  dubbo:
    name: dubbo-go-samples
    driver: bridge
