// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: seata.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"

	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	anypb "google.golang.org/protobuf/types/known/anypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusinessActionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	BranchId      int64                  `protobuf:"varint,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	ActionName    string                 `protobuf:"bytes,3,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	ActionContext map[string]*anypb.Any  `protobuf:"bytes,4,rep,name=action_context,json=actionContext,proto3" json:"action_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessActionContext) Reset() {
	*x = BusinessActionContext{}
	mi := &file_seata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessActionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessActionContext) ProtoMessage() {}

func (x *BusinessActionContext) ProtoReflect() protoreflect.Message {
	mi := &file_seata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessActionContext.ProtoReflect.Descriptor instead.
func (*BusinessActionContext) Descriptor() ([]byte, []int) {
	return file_seata_proto_rawDescGZIP(), []int{0}
}

func (x *BusinessActionContext) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

func (x *BusinessActionContext) GetBranchId() int64 {
	if x != nil {
		return x.BranchId
	}
	return 0
}

func (x *BusinessActionContext) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *BusinessActionContext) GetActionContext() map[string]*anypb.Any {
	if x != nil {
		return x.ActionContext
	}
	return nil
}

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_seata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_seata_proto_rawDescGZIP(), []int{1}
}

type PrepareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_seata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_seata_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type CommitRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BusinessActionContext *BusinessActionContext `protobuf:"bytes,1,opt,name=business_action_context,json=businessActionContext,proto3" json:"business_action_context,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_seata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_seata_proto_rawDescGZIP(), []int{3}
}

func (x *CommitRequest) GetBusinessActionContext() *BusinessActionContext {
	if x != nil {
		return x.BusinessActionContext
	}
	return nil
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_seata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_seata_proto_rawDescGZIP(), []int{4}
}

func (x *CommitResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type RollbackRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BusinessActionContext *BusinessActionContext `protobuf:"bytes,1,opt,name=business_action_context,json=businessActionContext,proto3" json:"business_action_context,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_seata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_seata_proto_rawDescGZIP(), []int{5}
}

func (x *RollbackRequest) GetBusinessActionContext() *BusinessActionContext {
	if x != nil {
		return x.BusinessActionContext
	}
	return nil
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_seata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_seata_proto_rawDescGZIP(), []int{6}
}

func (x *RollbackResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetActionNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionNameRequest) Reset() {
	*x = GetActionNameRequest{}
	mi := &file_seata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionNameRequest) ProtoMessage() {}

func (x *GetActionNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionNameRequest.ProtoReflect.Descriptor instead.
func (*GetActionNameRequest) Descriptor() ([]byte, []int) {
	return file_seata_proto_rawDescGZIP(), []int{7}
}

type GetActionNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionName    string                 `protobuf:"bytes,1,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionNameResponse) Reset() {
	*x = GetActionNameResponse{}
	mi := &file_seata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionNameResponse) ProtoMessage() {}

func (x *GetActionNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionNameResponse.ProtoReflect.Descriptor instead.
func (*GetActionNameResponse) Descriptor() ([]byte, []int) {
	return file_seata_proto_rawDescGZIP(), []int{8}
}

func (x *GetActionNameResponse) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

var File_seata_proto protoreflect.FileDescriptor

const file_seata_proto_rawDesc = "" +
	"\n" +
	"\vseata.proto\x12\aservice\x1a\x19google/protobuf/any.proto\"\x99\x02\n" +
	"\x15BusinessActionContext\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\x12\x1b\n" +
	"\tbranch_id\x18\x02 \x01(\x03R\bbranchId\x12\x1f\n" +
	"\vaction_name\x18\x03 \x01(\tR\n" +
	"actionName\x12X\n" +
	"\x0eaction_context\x18\x04 \x03(\v21.service.BusinessActionContext.ActionContextEntryR\ractionContext\x1aV\n" +
	"\x12ActionContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\x10\n" +
	"\x0ePrepareRequest\")\n" +
	"\x0fPrepareResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"g\n" +
	"\rCommitRequest\x12V\n" +
	"\x17business_action_context\x18\x01 \x01(\v2\x1e.service.BusinessActionContextR\x15businessActionContext\"(\n" +
	"\x0eCommitResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"i\n" +
	"\x0fRollbackRequest\x12V\n" +
	"\x17business_action_context\x18\x01 \x01(\v2\x1e.service.BusinessActionContextR\x15businessActionContext\"*\n" +
	"\x10RollbackResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"\x16\n" +
	"\x14GetActionNameRequest\"8\n" +
	"\x15GetActionNameResponse\x12\x1f\n" +
	"\vaction_name\x18\x01 \x01(\tR\n" +
	"actionName2\xac\x02\n" +
	"\fUserProvider\x12A\n" +
	"\fPrepareProxy\x12\x17.service.PrepareRequest\x1a\x18.service.PrepareResponse\x12>\n" +
	"\vCommitProxy\x12\x16.service.CommitRequest\x1a\x17.service.CommitResponse\x12D\n" +
	"\rRollbackProxy\x12\x18.service.RollbackRequest\x1a\x19.service.RollbackResponse\x12S\n" +
	"\x12GetActionNameProxy\x12\x1d.service.GetActionNameRequest\x1a\x1e.service.GetActionNameResponseBLZJgithub.com/apache/dubbo-go-samples/transcation/seata-go/triple/proto;protob\x06proto3"

var (
	file_seata_proto_rawDescOnce sync.Once
	file_seata_proto_rawDescData []byte
)

func file_seata_proto_rawDescGZIP() []byte {
	file_seata_proto_rawDescOnce.Do(func() {
		file_seata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seata_proto_rawDesc), len(file_seata_proto_rawDesc)))
	})
	return file_seata_proto_rawDescData
}

var file_seata_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_seata_proto_goTypes = []any{
	(*BusinessActionContext)(nil), // 0: service.BusinessActionContext
	(*PrepareRequest)(nil),        // 1: service.PrepareRequest
	(*PrepareResponse)(nil),       // 2: service.PrepareResponse
	(*CommitRequest)(nil),         // 3: service.CommitRequest
	(*CommitResponse)(nil),        // 4: service.CommitResponse
	(*RollbackRequest)(nil),       // 5: service.RollbackRequest
	(*RollbackResponse)(nil),      // 6: service.RollbackResponse
	(*GetActionNameRequest)(nil),  // 7: service.GetActionNameRequest
	(*GetActionNameResponse)(nil), // 8: service.GetActionNameResponse
	nil,                           // 9: service.BusinessActionContext.ActionContextEntry
	(*anypb.Any)(nil),             // 10: google.protobuf.Any
}
var file_seata_proto_depIdxs = []int32{
	9,  // 0: service.BusinessActionContext.action_context:type_name -> service.BusinessActionContext.ActionContextEntry
	0,  // 1: service.CommitRequest.business_action_context:type_name -> service.BusinessActionContext
	0,  // 2: service.RollbackRequest.business_action_context:type_name -> service.BusinessActionContext
	10, // 3: service.BusinessActionContext.ActionContextEntry.value:type_name -> google.protobuf.Any
	1,  // 4: service.UserProvider.PrepareProxy:input_type -> service.PrepareRequest
	3,  // 5: service.UserProvider.CommitProxy:input_type -> service.CommitRequest
	5,  // 6: service.UserProvider.RollbackProxy:input_type -> service.RollbackRequest
	7,  // 7: service.UserProvider.GetActionNameProxy:input_type -> service.GetActionNameRequest
	2,  // 8: service.UserProvider.PrepareProxy:output_type -> service.PrepareResponse
	4,  // 9: service.UserProvider.CommitProxy:output_type -> service.CommitResponse
	6,  // 10: service.UserProvider.RollbackProxy:output_type -> service.RollbackResponse
	8,  // 11: service.UserProvider.GetActionNameProxy:output_type -> service.GetActionNameResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_seata_proto_init() }
func file_seata_proto_init() {
	if File_seata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seata_proto_rawDesc), len(file_seata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seata_proto_goTypes,
		DependencyIndexes: file_seata_proto_depIdxs,
		MessageInfos:      file_seata_proto_msgTypes,
	}.Build()
	File_seata_proto = out.File
	file_seata_proto_goTypes = nil
	file_seata_proto_depIdxs = nil
}
