version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    restart: on-failure

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - jaeger-example

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_TCP_PORT=3306
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    ports:
      # Listen port for the Scribe transport
      - 9410:9410
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    depends_on:
      - storage

  storage:
    image: openzipkin/zipkin-mysql
    container_name: mysql
    ports:
      - 3307:3306


networks:
  jaeger-example: 
    