apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo-v2
  namespace: dubbo-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-demo
      version: v2
  template:
    metadata:
      labels:
        app: server-demo
        version: v2
    spec:
      containers:
        - name: server
          image: apache/dubbo-demo:dubbo-go-mesh-providerv2_0.0.1
          imagePullPolicy: Always
          ports:
            - name: grpc-tri
              containerPort: 50052
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /live
#              port: http-health
#            initialDelaySeconds: 10
#            periodSeconds: 5
#            timeoutSeconds: 1
#          readinessProbe:
#            httpGet:
#              path: /ready
#              port: http-health
#            initialDelaySeconds: 5
#            periodSeconds: 5
#            timeoutSeconds: 2
#          startupProbe:
#            httpGet:
#              path: /startup
#              port: http-health
#            failureThreshold: 30
#            initialDelaySeconds: 10
#            periodSeconds: 5
#            timeoutSeconds: 2