version: "3"

services:
  hangzouNacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8849:8848"
  shanghaiNacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-a
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8847:8848"