version: "3"

services:
  nacos:
    image: nacos/nacos-server:1.2.0
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
