apiVersion: v1
kind: Service
metadata:
  name: client-demo
  namespace: dubbo-demo
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: client-demo
  ports:
    - name: grpc-dubbo
      protocol: TCP
      port: 50052
      targetPort: 50052