version: '3'

services:
  etcd:
    image: "quay.io/coreos/etcd:latest"
    container_name: etcd
    environment:
      - ETCDCTL_API=3
    command: [
        "etcd",
        "--name=etcd0",
    ]
    ports:
      - "2379:2379"
      - "2380:2380"
    restart: always
